//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WHTConfig.rc
//
#define IDI_ICON                        101
#define IDI_MAGNET                      102
#define IDD_MAIN_DIALOG                 103
#define IDD_MAGNETOMETER_CALIB          104
#define IDR_ACCELERATORS                105
#define IDD_GYRO_ACCEL_CONFIG           106
#define IDI_GYRO                        107
#define IDD_CUSTOM_CURVES               108
#define IDR_WAV_BEEP                    109
#define IDC_PRG_AXIS_X                  1001
#define IDC_PRG_AXIS_Y                  1002
#define IDC_PRG_AXIS_Z                  1003
#define IDC_LBL_CALIB_STATUS            1004
#define IDC_LBL_GYRO_BIAS_X             1005
#define IDC_LBL_GYRO_BIAS_Y             1006
#define IDC_LBL_GYRO_BIAS_Z             1007
#define IDC_LBL_ACCEL_BIAS_X            1008
#define IDC_LBL_ACCEL_BIAS_Y            1009
#define IDC_LBL_ACCEL_BIAS_Z            1010
#define IDC_LBL_APPLIED_DRIFT_COMP      1011
#define IDC_LBL_NEW_DRIFT_COMP          1012
#define IDC_BTN_RESET_DRIFT_COMP        1013
#define IDC_BTN_SAVE_DRIFT_COMP         1014
#define IDC_CMB_YAW_CORRECT_METHOD      1015
#define IDC_STATUS_BAR                  1019
#define IDC_CMB_AXIS_RESPONSE           1020
#define IDC_BTN_DONGLE_SETTINGS         1021
#define IDC_LBL_AXIS_NUM_X              1022
#define IDC_LBL_AXIS_NUM_Y              1023
#define IDC_LBL_AXIS_NUM_Z              1024
#define IDC_BTN_MAG_CALIBRATION         1025
#define IDC_D3D                         1026
#define IDC_EDT_LOW_VOLTAGE             1026
#define IDC_LBL_RECENTER_BOUND_TO_DEVICE 1027
#define IDC_BTN_RESET_CAMERA            1028
#define IDC_CMB_ACTIVE_DEVICES          1028
#define IDC_LBL_RECENTER_BOUND_STATUS   1029
#define IDC_LBL_NUM_SAMPLES             1030
#define IDC_CMB_SLEEPING_MODE           1030
#define IDC_CMB_SLEEP_MODE              1030
#define IDC_LBL_RECENTER_BOUND_TO_DETAILS 1031
#define IDC_BTN_LOAD_RAW_POINTS         1032
#define IDC_CMB_TRACKER_ORIENTATION     1032
#define IDC_BTN_GYRO_ACCEL_CALIBRATION  1033
#define IDC_BTN_SAVE_RAW_POINTS         1034
#define IDC_LBL_AXIS_DEG_X              1034
#define IDC_BTN_TOGGLE_SAMPLING         1035
#define IDC_LBL_DISABLE_TGL_BOUND_STATUS 1035
#define IDC_ACC_GENERATE_TEST_DATA      1036
#define IDC_LBL_DISABLE_TGL_BOUND_TO_DEVICE 1036
#define IDC_BTN_CLEAR_ALL_SAMPLES       1037
#define IDC_LBL_DISABLE_TGL_BOUND_TO_DETAILS 1037
#define IDC_BTN_CLEAR_CALIBRATED_POINTS 1038
#define IDC_LBL_DISABLE_TGL_BOUND_STATUS2 1038
#define IDC_LBL_IS_ENABLED              1038
#define IDC_BTN_CALCULATE_CALIBRATION   1039
#define IDC_LBL_AXIS_DEG_Y              1039
#define IDC_LBL_RADIUS_X                1040
#define IDC_LBL_AXIS_NUM_Z2             1040
#define IDC_LBL_AXIS_DEG_Z              1040
#define IDC_LBL_RADIUS_Y                1041
#define IDC_LBL_RADIUS_Z                1042
#define IDC_LBL_CENTER_X_CALC           1043
#define IDC_LBL_CENTER_Y_CALC           1044
#define IDC_LBL_CENTER_Z_CALC           1045
#define IDC_LBL_MATRIX_1_CALC           1046
#define IDC_LBL_MATRIX_2_CALC           1047
#define IDC_LBL_MATRIX_3_CALC           1048
#define IDC_LBL_MATRIX_4_CALC           1049
#define IDC_LBL_MATRIX_5_CALC           1050
#define IDC_LBL_MATRIX_6_CALC           1051
#define IDC_LBL_FPS                     1052
#define IDC_LBL_NUMBER_OF_VERTICES      1053
#define IDC_CHK_FILTER_SAMPLES          1054
#define IDC_BTN_SEND_TO_DONGLE          1055
#define IDC_LBL_CENTER_X_DONGLE         1056
#define IDC_LBL_CENTER_Y_DONGLE         1057
#define IDC_LBL_CENTER_Z_DONGLE         1058
#define IDC_LBL_MATRIX_1_DONGLE         1059
#define IDC_LBL_MATRIX_2_DONGLE         1060
#define IDC_LBL_MATRIX_3_DONGLE         1061
#define IDC_LBL_MATRIX_4_DONGLE         1062
#define IDC_LBL_MATRIX_5_DONGLE         1063
#define IDC_LBL_MATRIX_6_DONGLE         1064
#define IDC_CHK_FILTER_SAMPLES2         1065
#define IDC_CHK_SHOW_DONGLE_CALIB_POINTS 1065
#define IDC_BTN_RECENTER_BIND           1065
#define IDC_BTN_RECENTER_UNBIND         1066
#define IDC_LBL_YAW_VALUE               1067
#define IDC_BTN_DISABLE_TGL_UNBIND      1067
#define IDC_LBL_SAMPLE_COUNT            1068
#define IDC_BTN_DISABLE_TGL_BIND        1068
#define IDC_BTN_RUN_GYRO_CALIBRATE      1069
#define IDC_LBL_MAGNETOMETER_CALIBRATION_STATUS 1070
#define IDC_LBL_GYRO_ACCEL_CALIBRATION_STATUS 1071
#define IDC_BTN_CUSTOM_CURVE            1072
#define IDC_CHK_AUDIO_ALERT             1073
#define IDC_SLD_MOUSE_SENS_X            1074
#define IDC_SLD_MOUSE_SENS_Y            1075
#define IDC_SLD_MOUSE_SENS_WHEEL        1076
#define IDC_SLD_JOYSTICK_SENS_X         1077
#define IDC_SLD_JOYSTICK_SENS_Y         1078
#define IDC_SLD_JOYSTICK_SENS_Z         1079
#define IDC_SLD_MAGNETOMETER_SENS       1080
#define IDC_ACC_CLEAR_MAG_CALIBRATION   40001
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
